"""Add target constraints and HOLD insight

Revision ID: 09e3728276a7
Revises: cd09038f20fb
Create Date: 2026-03-20 14:35:36.266023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e3728276a7'
down_revision: Union[str, None] = 'cd09038f20fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Postgres enum type modifications
    op.execute("ALTER TYPE tradeaction ADD VALUE IF NOT EXISTS 'HOLD'")
    op.execute("ALTER TYPE tradeaction ADD VALUE IF NOT EXISTS 'WATCH'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('target_price', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('stop_loss_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'stop_loss_price')
    op.drop_column('trades', 'target_price')
    # ### end Alembic commands ###
