"""Add strategy_profile

Revision ID: 0ce8c228a19d
Revises: fba7772a0e94
Create Date: 2026-02-24 14:46:35.508932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce8c228a19d'
down_revision: Union[str, None] = 'fba7772a0e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_config', sa.Column('strategy_profile', sa.Enum('BALANCED', 'AGGRESSIVE_DAY_TRADER', 'CONSERVATIVE_VALUE', 'MOMENTUM_SCALPER', name='strategyprofile'), nullable=False, server_default='BALANCED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_config', 'strategy_profile')
    # ### end Alembic commands ###
