"""add read_only role

Revision ID: 0d3f8c83f88f
Revises: dd29f29e0fd2
Create Date: 2026-03-05 09:57:42.310133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3f8c83f88f'
down_revision: Union[str, None] = 'dd29f29e0fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_read_only', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('linked_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['linked_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'linked_user_id')
    op.drop_column('users', 'is_read_only')
    # ### end Alembic commands ###
