"""Add bot_config percentages

Revision ID: cd09038f20fb
Revises: 0d3f8c83f88f
Create Date: 2026-03-20 13:19:10.625791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd09038f20fb'
down_revision: Union[str, None] = '0d3f8c83f88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
