"""Add multi-bot providers and allocations

Revision ID: dd29f29e0fd2
Revises: 0ce8c228a19d
Create Date: 2026-02-27 09:02:52.360436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd29f29e0fd2'
down_revision: Union[str, None] = '0ce8c228a19d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_config', sa.Column('openai_api_key', sa.String(length=255), nullable=True))
    op.add_column('bot_config', sa.Column('openai_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('bot_config', sa.Column('openai_allocation', sa.Float(), server_default='1000.0', nullable=False))
    op.add_column('bot_config', sa.Column('gemini_api_key', sa.String(length=255), nullable=True))
    op.add_column('bot_config', sa.Column('gemini_active', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('bot_config', sa.Column('gemini_allocation', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('bot_config', sa.Column('anthropic_api_key', sa.String(length=255), nullable=True))
    op.add_column('bot_config', sa.Column('anthropic_active', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('bot_config', sa.Column('anthropic_allocation', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('holdings', sa.Column('ai_provider', sa.String(length=50), nullable=True))
    op.add_column('trades', sa.Column('ai_provider', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'ai_provider')
    op.drop_column('holdings', 'ai_provider')
    op.drop_column('bot_config', 'anthropic_allocation')
    op.drop_column('bot_config', 'anthropic_active')
    op.drop_column('bot_config', 'anthropic_api_key')
    op.drop_column('bot_config', 'gemini_allocation')
    op.drop_column('bot_config', 'gemini_active')
    op.drop_column('bot_config', 'gemini_api_key')
    op.drop_column('bot_config', 'openai_allocation')
    op.drop_column('bot_config', 'openai_active')
    op.drop_column('bot_config', 'openai_api_key')
    # ### end Alembic commands ###
