"""Initial migration

Revision ID: fba7772a0e94
Revises: 
Create Date: 2026-02-24 14:42:50.568955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba7772a0e94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE bot_config ALTER COLUMN portfolio_allocation_type DROP DEFAULT")
    op.execute("ALTER TABLE bot_config ALTER COLUMN portfolio_allocation_type TYPE allocationtype USING portfolio_allocation_type::text::allocationtype")
    op.execute("ALTER TABLE bot_config ALTER COLUMN portfolio_allocation_type SET DEFAULT 'PERCENTAGE'::allocationtype")
    op.alter_column('bot_config', 'portfolio_allocation_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PERCENTAGE', 'FIXED_AMOUNT', name='allocationtype'),
               existing_nullable=False,
               existing_server_default=sa.text("'PERCENTAGE'::character varying"))
    op.drop_column('bot_config', 'stop_loss_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_config', sa.Column('stop_loss_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('bot_config', 'portfolio_allocation_type',
               existing_type=sa.Enum('PERCENTAGE', 'FIXED_AMOUNT', name='allocationtype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PERCENTAGE'::character varying"))
    # ### end Alembic commands ###
